const vocabData = {
  "unit1": {
    "title": "UNIT 01 문장을 이루는 요소",
    "words": [
      { "id": 1, "eng": "have a cold", "kor": "감기에 걸리다" },
      { "id": 2, "eng": "Chinese", "kor": "중국어" },
      { "id": 3, "eng": "floor", "kor": "바닥" },
      { "id": 4, "eng": "dirty", "kor": "더러운" },
      { "id": 5, "eng": "plate", "kor": "접시" },
      { "id": 6, "eng": "take a picture", "kor": "사진을 찍다" },
      { "id": 7, "eng": "start", "kor": "시작하다" },
      { "id": 8, "eng": "garden", "kor": "정원" },
      { "id": 9, "eng": "favorite", "kor": "가장 좋아하는" },
      { "id": 10, "eng": "subject", "kor": "과목" },
      { "id": 11, "eng": "basketball", "kor": "농구" },
      { "id": 12, "eng": "market", "kor": "시장" },
      { "id": 13, "eng": "at that time", "kor": "그때" },
      { "id": 14, "eng": "carry", "kor": "나르다" },
      { "id": 15, "eng": "question", "kor": "문제; 질문" },
      { "id": 16, "eng": "fix", "kor": "고치다" },
      { "id": 17, "eng": "brave", "kor": "용감한" },
      { "id": 18, "eng": "exciting", "kor": "신나는" },
      { "id": 19, "eng": "cleanly", "kor": "깨끗하게" },
      { "id": 20, "eng": "musical", "kor": "뮤지컬" },
      { "id": 21, "eng": "draw", "kor": "그리다" },
      { "id": 22, "eng": "smart", "kor": "똑똑한" },
      { "id": 23, "eng": "concert", "kor": "콘서트" },
      { "id": 24, "eng": "band", "kor": "밴드" },
      { "id": 25, "eng": "fireworks", "kor": "불꽃놀이" },
      { "id": 26, "eng": "writer", "kor": "작가" },
      { "id": 27, "eng": "guitar", "kor": "기타" },
      { "id": 28, "eng": "famous", "kor": "유명한" },
      { "id": 29, "eng": "painter", "kor": "화가" },
      { "id": 30, "eng": "cheap", "kor": "값싼" },
      { "id": 31, "eng": "then", "kor": "그때" },
      { "id": 32, "eng": "shy", "kor": "수줍은" },
      { "id": 33, "eng": "miss", "kor": "그리워하다" },
      { "id": 34, "eng": "bright", "kor": "밝은" },
      { "id": 35, "eng": "beach", "kor": "해변" },
      { "id": 36, "eng": "noise", "kor": "소음" },
      { "id": 37, "eng": "careful", "kor": "조심하는, 주의 깊은" },
      { "id": 38, "eng": "ready", "kor": "준비가 된" },
      { "id": 39, "eng": "mistake", "kor": "실수" },
      { "id": 40, "eng": "ending", "kor": "결말" },
      { "id": 41, "eng": "throw", "kor": "던지다" },
      { "id": 42, "eng": "empty", "kor": "빈" },
      { "id": 43, "eng": "open", "kor": "열리다; 열다" }
    ]
  },
  "unit2": {
    "title": "UNIT 02 1형식과 2형식",
    "words": [
      { "id": 1, "eng": "look", "kor": "~해 보이다" },
      { "id": 2, "eng": "sound", "kor": "~하게 들리다" },
      { "id": 3, "eng": "smell", "kor": "~한 냄새가 나다" },
      { "id": 4, "eng": "taste", "kor": "~한 맛이 나다" },
      { "id": 5, "eng": "delicious", "kor": "맛있는" },
      { "id": 6, "eng": "feel", "kor": "~하게 느껴지다" },
      { "id": 7, "eng": "bark", "kor": "(개가) 짖다" },
      { "id": 8, "eng": "loudly", "kor": "큰 소리로" },
      { "id": 9, "eng": "voice", "kor": "목소리" },
      { "id": 10, "eng": "pillow", "kor": "베개" },
      { "id": 11, "eng": "softly", "kor": "부드럽게" },
      { "id": 12, "eng": "sweet", "kor": "달콤한, 단" },
      { "id": 13, "eng": "laugh", "kor": "웃다" },
      { "id": 14, "eng": "hard", "kor": "열심히" },
      { "id": 15, "eng": "ring", "kor": "울리다" },
      { "id": 16, "eng": "stop", "kor": "정류장, 정거장" },
      { "id": 17, "eng": "beautiful", "kor": "아름다운" },
      { "id": 18, "eng": "rise", "kor": "(해, 달이) 뜨다" },
      { "id": 19, "eng": "scarf", "kor": "스카프" },
      { "id": 20, "eng": "soft", "kor": "부드러운" },
      { "id": 21, "eng": "bench", "kor": "벤치" },
      { "id": 22, "eng": "office", "kor": "사무실" },
      { "id": 23, "eng": "weather", "kor": "날씨" },
      { "id": 24, "eng": "lie", "kor": "거짓말; 거짓말하다" },
      { "id": 25, "eng": "interesting", "kor": "재미있는" },
      { "id": 26, "eng": "angrily", "kor": "화가 나서" },
      { "id": 27, "eng": "young", "kor": "어린, 젊은" },
      { "id": 28, "eng": "sour", "kor": "(맛이) 신" },
      { "id": 29, "eng": "arrive", "kor": "도착하다" },
      { "id": 30, "eng": "airport", "kor": "공항" },
      { "id": 31, "eng": "idea", "kor": "생각, 아이디어" },
      { "id": 32, "eng": "perfectly", "kor": "완벽하게" },
      { "id": 33, "eng": "quick", "kor": "빠른" },
      { "id": 34, "eng": "sweater", "kor": "스웨터" },
      { "id": 35, "eng": "set", "kor": "(해·달이) 지다" },
      { "id": 36, "eng": "moon", "kor": "달" },
      { "id": 37, "eng": "shine", "kor": "빛나다" },
      { "id": 38, "eng": "leaf", "kor": "(나뭇)잎" },
      { "id": 39, "eng": "fall", "kor": "떨어지다" },
      { "id": 40, "eng": "autumn", "kor": "가을" },
      { "id": 41, "eng": "flow", "kor": "흐르다" },
      { "id": 42, "eng": "plant", "kor": "식물" },
      { "id": 43, "eng": "tourist", "kor": "관광객" },
      { "id": 44, "eng": "village", "kor": "마을" },
      { "id": 45, "eng": "soon", "kor": "곧" },
      { "id": 46, "eng": "cousin", "kor": "사촌" },
      { "id": 47, "eng": "living room", "kor": "거실" }
    ]
  },
  "unit3": {
    "title": "UNIT 03 3형식 (동사+목적어)",
    "words": [
      { "id": 1, "eng": "sell", "kor": "팔다" },
      { "id": 2, "eng": "fresh", "kor": "신선한" },
      { "id": 3, "eng": "weekend", "kor": "주말" },
      { "id": 4, "eng": "snack", "kor": "간식" },
      { "id": 5, "eng": "science", "kor": "과학" },
      { "id": 6, "eng": "break", "kor": "깨뜨리다" },
      { "id": 7, "eng": "vase", "kor": "꽃병" },
      { "id": 8, "eng": "bring", "kor": "가져오다" },
      { "id": 9, "eng": "draw", "kor": "그리다" },
      { "id": 10, "eng": "wall", "kor": "벽" },
      { "id": 11, "eng": "a glass of", "kor": "한 잔의" },
      { "id": 12, "eng": "build", "kor": "짓다" },
      { "id": 13, "eng": "in class", "kor": "수업 중에" },
      { "id": 14, "eng": "practice", "kor": "연습하다" },
      { "id": 15, "eng": "exam", "kor": "시험" },
      { "id": 16, "eng": "invite", "kor": "초대하다" },
      { "id": 17, "eng": "parents", "kor": "부모" },
      { "id": 18, "eng": "understand", "kor": "이해하다" },
      { "id": 19, "eng": "free", "kor": "자유로운; 무료의" },
      { "id": 20, "eng": "spicy", "kor": "매운" },
      { "id": 21, "eng": "scissors", "kor": "가위" },
      { "id": 22, "eng": "history", "kor": "역사" },
      { "id": 23, "eng": "learn", "kor": "배우다" },
      { "id": 24, "eng": "move", "kor": "옮기다" },
      { "id": 25, "eng": "corner", "kor": "(방, 상자의) 구석" },
      { "id": 26, "eng": "solve", "kor": "해결하다, 풀다" },
      { "id": 27, "eng": "borrow", "kor": "빌리다" },
      { "id": 28, "eng": "kick", "kor": "(발로) 차다" },
      { "id": 29, "eng": "remember", "kor": "기억하다" },
      { "id": 30, "eng": "get", "kor": "받다" },
      { "id": 31, "eng": "board game", "kor": "보드게임" },
      { "id": 32, "eng": "water", "kor": "물을 주다" },
      { "id": 33, "eng": "join", "kor": "가입하다" },
      { "id": 34, "eng": "pick", "kor": "(과일을) 따다" },
      { "id": 35, "eng": "chef", "kor": "요리사" }
    ]
  },
  "unit4": {
    "title": "UNIT 04 4형식 (동사+목적어+목적어)",
    "words": [
      { "id": 1, "eng": "gift", "kor": "선물" },
      { "id": 2, "eng": "show", "kor": "보여 주다" },
      { "id": 3, "eng": "video", "kor": "영상, 비디오" },
      { "id": 4, "eng": "bring", "kor": "가져다주다" },
      { "id": 5, "eng": "secret", "kor": "비밀" },
      { "id": 6, "eng": "picture", "kor": "사진, 그림" },
      { "id": 7, "eng": "letter", "kor": "편지" },
      { "id": 8, "eng": "sweater", "kor": "스웨터" },
      { "id": 9, "eng": "album", "kor": "앨범" },
      { "id": 10, "eng": "juice", "kor": "주스" },
      { "id": 11, "eng": "message", "kor": "메시지" },
      { "id": 12, "eng": "medicine", "kor": "약" },
      { "id": 13, "eng": "child", "kor": "아이" },
      { "id": 14, "eng": "chocolate", "kor": "초콜릿" },
      { "id": 15, "eng": "cousin", "kor": "사촌" },
      { "id": 16, "eng": "coach", "kor": "(스포츠팀의) 코치" },
      { "id": 17, "eng": "rule", "kor": "규칙" },
      { "id": 18, "eng": "noodle", "kor": "국수" },
      { "id": 19, "eng": "recipe", "kor": "레시피, 조리법" },
      { "id": 20, "eng": "guest", "kor": "손님" },
      { "id": 21, "eng": "bracelet", "kor": "팔찌" },
      { "id": 22, "eng": "surprising", "kor": "놀라운" },
      { "id": 23, "eng": "hard", "kor": "어려운" },
      { "id": 24, "eng": "truth", "kor": "사실" },
      { "id": 25, "eng": "postcard", "kor": "엽서" },
      { "id": 26, "eng": "lie", "kor": "거짓말" },
      { "id": 27, "eng": "backpack", "kor": "책가방, 배낭" },
      { "id": 28, "eng": "magic trick", "kor": "마술 묘기" },
      { "id": 29, "eng": "map", "kor": "지도" },
      { "id": 30, "eng": "present", "kor": "선물" },
      { "id": 31, "eng": "number", "kor": "번호" },
      { "id": 32, "eng": "word", "kor": "단어" },
      { "id": 33, "eng": "calendar", "kor": "달력" },
      { "id": 34, "eng": "hot chocolate", "kor": "핫초코, 코코아" }
    ]
  },
  "unit5": {
    "title": "UNIT 05 5형식 (동사+목적어+보어)",
    "words": [
      { "id": 1, "eng": "joke", "kor": "농담" },
      { "id": 2, "eng": "keep", "kor": "(특정 상태를) 유지하다" },
      { "id": 3, "eng": "find", "kor": "~하다고 여기다" },
      { "id": 4, "eng": "difficult", "kor": "어려운" },
      { "id": 5, "eng": "famous", "kor": "유명한" },
      { "id": 6, "eng": "plant", "kor": "식물" },
      { "id": 7, "eng": "healthy", "kor": "건강한" },
      { "id": 8, "eng": "interesting", "kor": "재미있는" },
      { "id": 9, "eng": "warm", "kor": "따뜻한" },
      { "id": 10, "eng": "boring", "kor": "지루한" },
      { "id": 11, "eng": "proud", "kor": "자랑스러운" },
      { "id": 12, "eng": "honest", "kor": "정직한" },
      { "id": 13, "eng": "seat belt", "kor": "안전벨트" },
      { "id": 14, "eng": "wet", "kor": "젖은" },
      { "id": 15, "eng": "brave", "kor": "용감한" },
      { "id": 16, "eng": "exercise", "kor": "운동" },
      { "id": 17, "eng": "hero", "kor": "영웅" },
      { "id": 18, "eng": "nail", "kor": "손톱" },
      { "id": 19, "eng": "thirsty", "kor": "목마른" },
      { "id": 20, "eng": "neighbor", "kor": "이웃" },
      { "id": 21, "eng": "exciting", "kor": "재미있는" },
      { "id": 22, "eng": "smell", "kor": "냄새" },
      { "id": 23, "eng": "oven", "kor": "오븐" },
      { "id": 24, "eng": "sharp", "kor": "뾰족한" },
      { "id": 25, "eng": "specially", "kor": "특별히" },
      { "id": 26, "eng": "simple", "kor": "간단한" },
      { "id": 27, "eng": "worried", "kor": "걱정하는" },
      { "id": 28, "eng": "Earth", "kor": "지구" },
      { "id": 29, "eng": "dry", "kor": "마른, 건조한" },
      { "id": 30, "eng": "problem", "kor": "문제" },
      { "id": 31, "eng": "calm", "kor": "차분한, 침착한" },
      { "id": 32, "eng": "expensive", "kor": "비싼" },
      { "id": 33, "eng": "blanket", "kor": "담요" },
      { "id": 34, "eng": "show", "kor": "공연" },
      { "id": 35, "eng": "clear", "kor": "분명한" }
    ]
  },
  "unit6": {
    "title": "UNIT 06 명사처럼 쓰이는 동명사 1",
    "words": [
      { "id": 1, "eng": "health", "kor": "건강" },
      { "id": 2, "eng": "lie", "kor": "거짓말; 누워 있다" },
      { "id": 3, "eng": "grade", "kor": "성적" },
      { "id": 4, "eng": "hobby", "kor": "취미" },
      { "id": 5, "eng": "activity", "kor": "활동" },
      { "id": 6, "eng": "helpful", "kor": "도움이 되는" },
      { "id": 7, "eng": "others", "kor": "다른 사람들" },
      { "id": 8, "eng": "important", "kor": "중요한" },
      { "id": 9, "eng": "habit", "kor": "습관; 버릇" },
      { "id": 10, "eng": "bite", "kor": "깨물다" },
      { "id": 11, "eng": "rule", "kor": "규칙" },
      { "id": 12, "eng": "follow", "kor": "따르다" },
      { "id": 13, "eng": "wait in line", "kor": "줄을 서서 기다리다" },
      { "id": 14, "eng": "comfortable", "kor": "편안한" },
      { "id": 15, "eng": "yoga", "kor": "요가" },
      { "id": 16, "eng": "practice", "kor": "연습하다" },
      { "id": 17, "eng": "part", "kor": "부분" },
      { "id": 18, "eng": "dangerous", "kor": "위험한" },
      { "id": 19, "eng": "thing", "kor": "것" },
      { "id": 20, "eng": "fast food", "kor": "패스트푸드" },
      { "id": 21, "eng": "close", "kor": "가까이" },
      { "id": 22, "eng": "save", "kor": "저축하다" },
      { "id": 23, "eng": "necessary", "kor": "필수의" },
      { "id": 24, "eng": "future", "kor": "미래" },
      { "id": 25, "eng": "design", "kor": "디자인하다" },
      { "id": 26, "eng": "clothes", "kor": "옷" },
      { "id": 27, "eng": "brush", "kor": "닦다" },
      { "id": 28, "eng": "step", "kor": "단계" },
      { "id": 29, "eng": "take a walk", "kor": "산책하다" },
      { "id": 30, "eng": "tie", "kor": "묶다" },
      { "id": 31, "eng": "cartoon", "kor": "만화" },
      { "id": 32, "eng": "circle", "kor": "동그라미, 원" },
      { "id": 33, "eng": "roller coaster", "kor": "롤러코스터" },
      { "id": 34, "eng": "ski", "kor": "스키를 타다" },
      { "id": 35, "eng": "popular", "kor": "인기 있는" },
      { "id": 36, "eng": "perfect score", "kor": "만점, 백 점" },
      { "id": 37, "eng": "talent", "kor": "재능" },
      { "id": 38, "eng": "check", "kor": "확인하다" }
    ]
  }
};