const vocabData = {
  "unit1": {
    "title": "UNIT 01 문장을 이루는 요소",
    "words": [
      { "id": 1, "eng": "have a cold", "kor": "감기에 걸리다" },
      { "id": 2, "eng": "Chinese", "kor": "중국어" },
      { "id": 3, "eng": "floor", "kor": "바닥" },
      { "id": 4, "eng": "dirty", "kor": "더러운" },
      { "id": 5, "eng": "plate", "kor": "접시" },
      { "id": 6, "eng": "take a picture", "kor": "사진을 찍다" },
      { "id": 7, "eng": "start", "kor": "시작하다" },
      { "id": 8, "eng": "garden", "kor": "정원" },
      { "id": 9, "eng": "favorite", "kor": "가장 좋아하는" },
      { "id": 10, "eng": "subject", "kor": "과목" },
      { "id": 11, "eng": "basketball", "kor": "농구" },
      { "id": 12, "eng": "market", "kor": "시장" },
      { "id": 13, "eng": "at that time", "kor": "그때" },
      { "id": 14, "eng": "carry", "kor": "나르다" },
      { "id": 15, "eng": "question", "kor": "문제; 질문" },
      { "id": 16, "eng": "fix", "kor": "고치다" },
      { "id": 17, "eng": "brave", "kor": "용감한" },
      { "id": 18, "eng": "exciting", "kor": "신나는" },
      { "id": 19, "eng": "cleanly", "kor": "깨끗하게" },
      { "id": 20, "eng": "musical", "kor": "뮤지컬" },
      { "id": 21, "eng": "draw", "kor": "그리다" },
      { "id": 22, "eng": "smart", "kor": "똑똑한" },
      { "id": 23, "eng": "concert", "kor": "콘서트" },
      { "id": 24, "eng": "band", "kor": "밴드" },
      { "id": 25, "eng": "fireworks", "kor": "불꽃놀이" },
      { "id": 26, "eng": "writer", "kor": "작가" },
      { "id": 27, "eng": "guitar", "kor": "기타" },
      { "id": 28, "eng": "famous", "kor": "유명한" },
      { "id": 29, "eng": "painter", "kor": "화가" },
      { "id": 30, "eng": "cheap", "kor": "값싼" },
      { "id": 31, "eng": "then", "kor": "그때" },
      { "id": 32, "eng": "shy", "kor": "수줍은" },
      { "id": 33, "eng": "miss", "kor": "그리워하다" },
      { "id": 34, "eng": "bright", "kor": "밝은" },
      { "id": 35, "eng": "beach", "kor": "해변" },
      { "id": 36, "eng": "noise", "kor": "소음" },
      { "id": 37, "eng": "careful", "kor": "조심하는, 주의 깊은" },
      { "id": 38, "eng": "ready", "kor": "준비가 된" },
      { "id": 39, "eng": "mistake", "kor": "실수" },
      { "id": 40, "eng": "ending", "kor": "결말" },
      { "id": 41, "eng": "throw", "kor": "던지다" },
      { "id": 42, "eng": "empty", "kor": "빈" },
      { "id": 43, "eng": "open", "kor": "열리다; 열다" }
    ]
  },
  "unit2": {
    "title": "UNIT 02 1형식과 2형식",
    "words": [
      { "id": 1, "eng": "look", "kor": "~해 보이다" },
      { "id": 2, "eng": "sound", "kor": "~하게 들리다" },
      { "id": 3, "eng": "smell", "kor": "~한 냄새가 나다" },
      { "id": 4, "eng": "taste", "kor": "~한 맛이 나다" },
      { "id": 5, "eng": "delicious", "kor": "맛있는" },
      { "id": 6, "eng": "feel", "kor": "~하게 느껴지다" },
      { "id": 7, "eng": "bark", "kor": "(개가) 짓다" },
      { "id": 8, "eng": "loudly", "kor": "큰 소리로" },
      { "id": 9, "eng": "voice", "kor": "목소리" },
      { "id": 10, "eng": "pillow", "kor": "베개" },
      { "id": 11, "eng": "softly", "kor": "부드럽게" },
      { "id": 12, "eng": "sweet", "kor": "달콤한, 단" },
      { "id": 13, "eng": "laugh", "kor": "웃다" },
      { "id": 14, "eng": "hard", "kor": "열심히" },
      { "id": 15, "eng": "ring", "kor": "울리다" },
      { "id": 16, "eng": "stop", "kor": "정류장, 정거장" },
      { "id": 17, "eng": "beautiful", "kor": "아름다운" },
      { "id": 18, "eng": "rise", "kor": "(해, 달이) 뜨다" },
      { "id": 19, "eng": "scarf", "kor": "스카프" },
      { "id": 20, "eng": "soft", "kor": "부드러운" },
      { "id": 21, "eng": "bench", "kor": "벤치" },
      { "id": 22, "eng": "office", "kor": "사무실" },
      { "id": 23, "eng": "weather", "kor": "날씨" },
      { "id": 24, "eng": "lie", "kor": "거짓말; 거짓말하다" },
      { "id": 25, "eng": "interesting", "kor": "재미있는" },
      { "id": 26, "eng": "angrily", "kor": "화가 나서" },
      { "id": 27, "eng": "young", "kor": "어린, 젊은" },
      { "id": 28, "eng": "sour", "kor": "(맛이) 신" },
      { "id": 29, "eng": "arrive", "kor": "도착하다" },
      { "id": 30, "eng": "airport", "kor": "공항" },
      { "id": 31, "eng": "idea", "kor": "생각, 아이디어" },
      { "id": 32, "eng": "perfectly", "kor": "완벽하게" },
      { "id": 33, "eng": "quick", "kor": "빠른" },
      { "id": 34, "eng": "sweater", "kor": "스웨터" },
      { "id": 35, "eng": "set", "kor": "(해·달이) 지다" },
      { "id": 36, "eng": "moon", "kor": "달" },
      { "id": 37, "eng": "shine", "kor": "빛나다" },
      { "id": 38, "eng": "leaf", "kor": "(나뭇)잎" },
      { "id": 39, "eng": "fall", "kor": "떨어지다" },
      { "id": 40, "eng": "autumn", "kor": "가을" },
      { "id": 41, "eng": "flow", "kor": "흐르다" },
      { "id": 42, "eng": "plant", "kor": "식물" },
      { "id": 43, "eng": "tourist", "kor": "관광객" },
      { "id": 44, "eng": "village", "kor": "마을" },
      { "id": 45, "eng": "soon", "kor": "곧" },
      { "id": 46, "eng": "cousin", "kor": "사촌" },
      { "id": 47, "eng": "living room", "kor": "거실" }
    ]
  },
  "unit3": {
    "title": "UNIT 03 3형식 (동사+목적어)",
    "words": [
      { "id": 1, "eng": "sell", "kor": "팔다" },
      { "id": 2, "eng": "fresh", "kor": "신선한" },
      { "id": 3, "eng": "weekend", "kor": "주말" },
      { "id": 4, "eng": "snack", "kor": "간식" },
      { "id": 5, "eng": "science", "kor": "과학" },
      { "id": 6, "eng": "break", "kor": "깨뜨리다" },
      { "id": 7, "eng": "vase", "kor": "꽃병" },
      { "id": 8, "eng": "bring", "kor": "가져오다" },
      { "id": 9, "eng": "draw", "kor": "그리다" },
      { "id": 10, "eng": "wall", "kor": "벽" },
      { "id": 11, "eng": "a glass of", "kor": "한 잔의" },
      { "id": 12, "eng": "build", "kor": "짓다" },
      { "id": 13, "eng": "in class", "kor": "수업 중에" },
      { "id": 14, "eng": "practice", "kor": "연습하다" },
      { "id": 15, "eng": "exam", "kor": "시험" },
      { "id": 16, "eng": "invite", "kor": "초대하다" },
      { "id": 17, "eng": "parents", "kor": "부모" },
      { "id": 18, "eng": "understand", "kor": "이해하다" },
      { "id": 19, "eng": "free", "kor": "자유로운; 무료의" },
      { "id": 20, "eng": "spicy", "kor": "매운" },
      { "id": 21, "eng": "scissors", "kor": "가위" },
      { "id": 22, "eng": "history", "kor": "역사" },
      { "id": 23, "eng": "learn", "kor": "배우다" },
      { "id": 24, "eng": "move", "kor": "옮기다" },
      { "id": 25, "eng": "corner", "kor": "(방, 상자의) 구석" },
      { "id": 26, "eng": "solve", "kor": "해결하다, 풀다" },
      { "id": 27, "eng": "borrow", "kor": "빌리다" },
      { "id": 28, "eng": "kick", "kor": "(발로) 차다" },
      { "id": 29, "eng": "remember", "kor": "기억하다" },
      { "id": 30, "eng": "get", "kor": "받다" },
      { "id": 31, "eng": "board game", "kor": "보드게임" },
      { "id": 32, "eng": "water", "kor": "물을 주다" },
      { "id": 33, "eng": "join", "kor": "가입하다" },
      { "id": 34, "eng": "pick", "kor": "(과일을) 따다" },
      { "id": 35, "eng": "chef", "kor": "요리사" }
    ]
  },
  "unit4": {
    "title": "UNIT 04 4형식 (동사+목적어+목적어)",
    "words": [
      { "id": 1, "eng": "gift", "kor": "선물" },
      { "id": 2, "eng": "show", "kor": "보여 주다" },
      { "id": 3, "eng": "video", "kor": "영상, 비디오" },
      { "id": 4, "eng": "bring", "kor": "가져다주다" },
      { "id": 5, "eng": "secret", "kor": "비밀" },
      { "id": 6, "eng": "picture", "kor": "사진, 그림" },
      { "id": 7, "eng": "letter", "kor": "편지" },
      { "id": 8, "eng": "sweater", "kor": "스웨터" },
      { "id": 9, "eng": "album", "kor": "앨범" },
      { "id": 10, "eng": "juice", "kor": "주스" },
      { "id": 11, "eng": "message", "kor": "메시지" },
      { "id": 12, "eng": "medicine", "kor": "약" },
      { "id": 13, "eng": "child", "kor": "아이" },
      { "id": 14, "eng": "chocolate", "kor": "초콜릿" },
      { "id": 15, "eng": "cousin", "kor": "사촌" },
      { "id": 16, "eng": "coach", "kor": "(스포츠팀의) 코치" },
      { "id": 17, "eng": "rule", "kor": "규칙" },
      { "id": 18, "eng": "noodle", "kor": "국수" },
      { "id": 19, "eng": "recipe", "kor": "레시피, 조리법" },
      { "id": 20, "eng": "guest", "kor": "손님" },
      { "id": 21, "eng": "bracelet", "kor": "팔찌" },
      { "id": 22, "eng": "surprising", "kor": "놀라운" },
      { "id": 23, "eng": "hard", "kor": "어려운" },
      { "id": 24, "eng": "truth", "kor": "사실" },
      { "id": 25, "eng": "postcard", "kor": "엽서" },
      { "id": 26, "eng": "lie", "kor": "거짓말" },
      { "id": 27, "eng": "backpack", "kor": "책가방, 배낭" },
      { "id": 28, "eng": "magic trick", "kor": "마술 묘기" },
      { "id": 29, "eng": "map", "kor": "지도" },
      { "id": 30, "eng": "present", "kor": "선물" },
      { "id": 31, "eng": "number", "kor": "번호" },
      { "id": 32, "eng": "word", "kor": "단어" },
      { "id": 33, "eng": "calendar", "kor": "달력" },
      { "id": 34, "eng": "hot chocolate", "kor": "핫초코, 코코아" }
    ]
  },
  "unit5": {
    "title": "UNIT 05 5형식 (동사+목적어+보어)",
    "words": [
      { "id": 1, "eng": "joke", "kor": "농담" },
      { "id": 2, "eng": "keep", "kor": "(특정 상태를) 유지하다" },
      { "id": 3, "eng": "find", "kor": "~하다고 여기다" },
      { "id": 4, "eng": "difficult", "kor": "어려운" },
      { "id": 5, "eng": "famous", "kor": "유명한" },
      { "id": 6, "eng": "plant", "kor": "식물" },
      { "id": 7, "eng": "healthy", "kor": "건강한" },
      { "id": 8, "eng": "interesting", "kor": "재미있는" },
      { "id": 9, "eng": "warm", "kor": "따뜻한" },
      { "id": 10, "eng": "boring", "kor": "지루한" },
      { "id": 11, "eng": "proud", "kor": "자랑스러운" },
      { "id": 12, "eng": "honest", "kor": "정직한" },
      { "id": 13, "eng": "seat belt", "kor": "안전벨트" },
      { "id": 14, "eng": "wet", "kor": "젖은" },
      { "id": 15, "eng": "brave", "kor": "용감한" },
      { "id": 16, "eng": "exercise", "kor": "운동" },
      { "id": 17, "eng": "hero", "kor": "영웅" },
      { "id": 18, "eng": "nail", "kor": "손톱" },
      { "id": 19, "eng": "thirsty", "kor": "목마른" },
      { "id": 20, "eng": "neighbor", "kor": "이웃" },
      { "id": 21, "eng": "exciting", "kor": "재미있는" },
      { "id": 22, "eng": "smell", "kor": "냄새" },
      { "id": 23, "eng": "oven", "kor": "오븐" },
      { "id": 24, "eng": "sharp", "kor": "뾰족한" },
      { "id": 25, "eng": "specially", "kor": "특별히" },
      { "id": 26, "eng": "simple", "kor": "간단한" },
      { "id": 27, "eng": "worried", "kor": "걱정하는" },
      { "id": 28, "eng": "Earth", "kor": "지구" },
      { "id": 29, "eng": "dry", "kor": "마른, 건조한" },
      { "id": 30, "eng": "problem", "kor": "문제" },
      { "id": 31, "eng": "calm", "kor": "차분한, 침착한" },
      { "id": 32, "eng": "expensive", "kor": "비싼" },
      { "id": 33, "eng": "blanket", "kor": "담요" },
      { "id": 34, "eng": "show", "kor": "공연" },
      { "id": 35, "eng": "clear", "kor": "분명한" }
    ]
  },
  "unit6": {
    "title": "UNIT 06 명사처럼 쓰이는 동명사 1",
    "words": [
      { "id": 1, "eng": "health", "kor": "건강" },
      { "id": 2, "eng": "lie", "kor": "거짓말; 누워 있다" },
      { "id": 3, "eng": "grade", "kor": "성적" },
      { "id": 4, "eng": "hobby", "kor": "취미" },
      { "id": 5, "eng": "activity", "kor": "활동" },
      { "id": 6, "eng": "helpful", "kor": "도움이 되는" },
      { "id": 7, "eng": "others", "kor": "다른 사람들" },
      { "id": 8, "eng": "important", "kor": "중요한" },
      { "id": 9, "eng": "habit", "kor": "습관; 버릇" },
      { "id": 10, "eng": "bite", "kor": "깨물다" },
      { "id": 11, "eng": "rule", "kor": "규칙" },
      { "id": 12, "eng": "follow", "kor": "따르다" },
      { "id": 13, "eng": "wait in line", "kor": "줄을 서서 기다리다" },
      { "id": 14, "eng": "comfortable", "kor": "편안한" },
      { "id": 15, "eng": "yoga", "kor": "요가" },
      { "id": 16, "eng": "practice", "kor": "연습하다" },
      { "id": 17, "eng": "part", "kor": "부분" },
      { "id": 18, "eng": "dangerous", "kor": "위험한" },
      { "id": 19, "eng": "thing", "kor": "것" },
      { "id": 20, "eng": "fast food", "kor": "패스트푸드" },
      { "id": 21, "eng": "close", "kor": "가까이" },
      { "id": 22, "eng": "save", "kor": "저축하다" },
      { "id": 23, "eng": "necessary", "kor": "필수의" },
      { "id": 24, "eng": "future", "kor": "미래" },
      { "id": 25, "eng": "design", "kor": "디자인하다" },
      { "id": 26, "eng": "clothes", "kor": "옷" },
      { "id": 27, "eng": "brush", "kor": "닦다" },
      { "id": 28, "eng": "step", "kor": "단계" },
      { "id": 29, "eng": "take a walk", "kor": "산책하다" },
      { "id": 30, "eng": "tie", "kor": "묶다" },
      { "id": 31, "eng": "cartoon", "kor": "만화" },
      { "id": 32, "eng": "circle", "kor": "동그라미, 원" },
      { "id": 33, "eng": "roller coaster", "kor": "롤러코스터" },
      { "id": 34, "eng": "ski", "kor": "스키를 타다" },
      { "id": 35, "eng": "popular", "kor": "인기 있는" },
      { "id": 36, "eng": "perfect score", "kor": "만점, 백 점" },
      { "id": 37, "eng": "talent", "kor": "재능" },
      { "id": 38, "eng": "check", "kor": "확인하다" }
    ]
  },
  "unit7": {
    "title": "UNIT 07 명사처럼 쓰이는 동명사 2",
    "words": [
      { "id": 1, "eng": "enjoy", "kor": "즐기다" },
      { "id": 2, "eng": "pool", "kor": "수영장" },
      { "id": 3, "eng": "keep", "kor": "계속하다" },
      { "id": 4, "eng": "give up", "kor": "포기하다" },
      { "id": 5, "eng": "avoid", "kor": "피하다" },
      { "id": 6, "eng": "mind", "kor": "신경 쓰다" },
      { "id": 7, "eng": "turn off", "kor": "(전기 등을) 끄다" },
      { "id": 8, "eng": "make noise", "kor": "소음을 내다" },
      { "id": 9, "eng": "wood", "kor": "숲" },
      { "id": 10, "eng": "wash the dishes", "kor": "설거지하다" },
      { "id": 11, "eng": "act", "kor": "연기하다; 행동하다" },
      { "id": 12, "eng": "play", "kor": "연극" },
      { "id": 13, "eng": "sandcastle", "kor": "모래성" },
      { "id": 14, "eng": "cartoon", "kor": "만화" },
      { "id": 15, "eng": "dessert", "kor": "디저트" },
      { "id": 16, "eng": "bake", "kor": "굽다" },
      { "id": 17, "eng": "question", "kor": "질문" },
      { "id": 18, "eng": "go to the movies", "kor": "영화 보러 가다" },
      { "id": 19, "eng": "truth", "kor": "진실" },
      { "id": 20, "eng": "by", "kor": "~옆에, ~가에" },
      { "id": 21, "eng": "board game", "kor": "보드게임" },
      { "id": 22, "eng": "soda", "kor": "탄산음료" },
      { "id": 23, "eng": "simple", "kor": "간단한" },
      { "id": 24, "eng": "meal", "kor": "식사" },
      { "id": 25, "eng": "stranger", "kor": "낯선 사람" },
      { "id": 26, "eng": "go on a picnic", "kor": "소풍 가다" },
      { "id": 27, "eng": "in front of", "kor": "~앞에서" },
      { "id": 28, "eng": "worry", "kor": "걱정하다" },
      { "id": 29, "eng": "knock", "kor": "두드리다" },
      { "id": 30, "eng": "go out", "kor": "외출하다" },
      { "id": 31, "eng": "skate", "kor": "스케이트 타다" }
    ]
  },
  "unit8": {
    "title": "UNIT 08 명사처럼 쓰이는 to부정사 1",
    "words": [
      { "id": 1, "eng": "goal", "kor": "목표" },
      { "id": 2, "eng": "lose weight", "kor": "체중을 줄이다" },
      { "id": 3, "eng": "pilot", "kor": "조종사" },
      { "id": 4, "eng": "wish", "kor": "소원, 바람" },
      { "id": 5, "eng": "collect", "kor": "모으다, 수집하다" },
      { "id": 6, "eng": "useful", "kor": "유용한" },
      { "id": 7, "eng": "vegetable", "kor": "채소" },
      { "id": 8, "eng": "hope", "kor": "희망, 바람" },
      { "id": 9, "eng": "history", "kor": "역사" },
      { "id": 10, "eng": "visit", "kor": "방문하다" },
      { "id": 11, "eng": "rule", "kor": "규칙" },
      { "id": 12, "eng": "paint", "kor": "페인트를 칠하다" },
      { "id": 13, "eng": "promise", "kor": "약속" },
      { "id": 14, "eng": "dangerous", "kor": "위험한" },
      { "id": 15, "eng": "wake up", "kor": "일어나다" },
      { "id": 16, "eng": "early", "kor": "일찍" },
      { "id": 17, "eng": "take a walk", "kor": "산책하다" },
      { "id": 18, "eng": "on time", "kor": "제때에" },
      { "id": 19, "eng": "design", "kor": "디자인하다, 설계하다" },
      { "id": 20, "eng": "bakery", "kor": "빵집" },
      { "id": 21, "eng": "enough", "kor": "충분한" },
      { "id": 22, "eng": "race", "kor": "경주" },
      { "id": 23, "eng": "novel", "kor": "소설" }
    ]
  },
  "unit9": {
    "title": "UNIT 09 명사처럼 쓰이는 to부정사 2",
    "words": [
      { "id": 1, "eng": "decide", "kor": "결정하다" },
      { "id": 2, "eng": "hope", "kor": "바라다" },
      { "id": 3, "eng": "soon", "kor": "곧" },
      { "id": 4, "eng": "expect", "kor": "기대하다" },
      { "id": 5, "eng": "laugh", "kor": "웃다" },
      { "id": 6, "eng": "promise", "kor": "약속하다, 약속" },
      { "id": 7, "eng": "call", "kor": "전화하다" },
      { "id": 8, "eng": "aunt", "kor": "이모, 고모, 숙모" },
      { "id": 9, "eng": "join", "kor": "가입하다" },
      { "id": 10, "eng": "club", "kor": "동아리" },
      { "id": 11, "eng": "Taekwondo", "kor": "태권도" },
      { "id": 12, "eng": "move", "kor": "옮기다" },
      { "id": 13, "eng": "pass", "kor": "합격하다" },
      { "id": 14, "eng": "French", "kor": "프랑스어" },
      { "id": 15, "eng": "pianist", "kor": "피아니스트" },
      { "id": 16, "eng": "something", "kor": "무엇" },
      { "id": 17, "eng": "go on a picnic", "kor": "소풍을 가다" },
      { "id": 18, "eng": "share", "kor": "나누다" },
      { "id": 19, "eng": "truth", "kor": "사실" },
      { "id": 20, "eng": "bark", "kor": "짓다" },
      { "id": 21, "eng": "present", "kor": "선물" },
      { "id": 22, "eng": "France", "kor": "프랑스" },
      { "id": 23, "eng": "museum", "kor": "박물관" },
      { "id": 24, "eng": "country", "kor": "시골" }
    ]
  },
  "unit10": {
    "title": "UNIT 10 형용사와 부사처럼 쓰이는 to부정사",
    "words": [
      { "id": 1, "eng": "leave", "kor": "떠나다" },
      { "id": 2, "eng": "place", "kor": "장소, 곳" },
      { "id": 3, "eng": "catch", "kor": "잡아타다" },
      { "id": 4, "eng": "hard", "kor": "열심히" },
      { "id": 5, "eng": "follow", "kor": "따르다" },
      { "id": 6, "eng": "return", "kor": "반납하다" },
      { "id": 7, "eng": "rest", "kor": "쉬다" },
      { "id": 8, "eng": "borrow", "kor": "빌리다" },
      { "id": 9, "eng": "race", "kor": "경주" },
      { "id": 10, "eng": "turn on", "kor": "~을 켜다" },
      { "id": 11, "eng": "raise", "kor": "들어 올리다" },
      { "id": 12, "eng": "hide", "kor": "숨다" },
      { "id": 13, "eng": "take notes", "kor": "메모하다, 기록하다" },
      { "id": 14, "eng": "look for", "kor": "찾다" },
      { "id": 15, "eng": "say goodbye", "kor": "작별 인사를 하다" },
      { "id": 16, "eng": "chopsticks", "kor": "젓가락" },
      { "id": 17, "eng": "noodle", "kor": "국수" },
      { "id": 18, "eng": "a lot of", "kor": "많은" },
      { "id": 19, "eng": "exam", "kor": "시험" },
      { "id": 20, "eng": "way", "kor": "길" },
      { "id": 21, "eng": "work", "kor": "일; 일하다, 노력하다" },
      { "id": 22, "eng": "go back", "kor": "돌아가다" },
      { "id": 23, "eng": "enter", "kor": "들어갈다" },
      { "id": 24, "eng": "board", "kor": "칠판" },
      { "id": 25, "eng": "on time", "kor": "제시각에" },
      { "id": 26, "eng": "chance", "kor": "기회" },
      { "id": 27, "eng": "funny", "kor": "웃긴" },
      { "id": 28, "eng": "arrive", "kor": "도착하다" },
      { "id": 29, "eng": "seat", "kor": "자리" }
    ]
  },
  "unit11": {
    "title": "UNIT 11 의문사+will/can 의문문",
    "words": [
      { "id": 1, "eng": "invite", "kor": "초대하다" },
      { "id": 2, "eng": "grandparents", "kor": "조부모" },
      { "id": 3, "eng": "feed", "kor": "먹이를 주다" },
      { "id": 4, "eng": "robot", "kor": "로봇" },
      { "id": 5, "eng": "airport", "kor": "공항" },
      { "id": 6, "eng": "result", "kor": "결과" },
      { "id": 7, "eng": "weekend", "kor": "주말" },
      { "id": 8, "eng": "stay", "kor": "머무르다" },
      { "id": 9, "eng": "Spanish", "kor": "스페인어" },
      { "id": 10, "eng": "classmate", "kor": "반 친구" },
      { "id": 11, "eng": "park", "kor": "세우다, 주차하다" },
      { "id": 12, "eng": "in front of", "kor": "~ 앞에" },
      { "id": 13, "eng": "aquarium", "kor": "수족관" },
      { "id": 14, "eng": "exercise", "kor": "운동하다" },
      { "id": 15, "eng": "from", "kor": "~에서" },
      { "id": 16, "eng": "camping", "kor": "캠핑" },
      { "id": 17, "eng": "see the doctor", "kor": "병원에 가다" },
      { "id": 18, "eng": "pasta", "kor": "파스타" },
      { "id": 19, "eng": "set the table", "kor": "상을 차리다" },
      { "id": 20, "eng": "practice", "kor": "연습하다" }
    ]
  },
  "unit12": {
    "title": "UNIT 12 접속사 and/but/or/so",
    "words": [
      { "id": 1, "eng": "light", "kor": "가벼운" },
      { "id": 2, "eng": "dessert", "kor": "디저트, 후식" },
      { "id": 3, "eng": "cheap", "kor": "(값이) 싼" },
      { "id": 4, "eng": "spicy", "kor": "매운" },
      { "id": 5, "eng": "expensive", "kor": "비싼" },
      { "id": 6, "eng": "say hi", "kor": "인사하다" },
      { "id": 7, "eng": "go to the doctor", "kor": "병원에 가다" },
      { "id": 8, "eng": "all day", "kor": "하루 종일" },
      { "id": 9, "eng": "lazy", "kor": "게으른" },
      { "id": 10, "eng": "miss", "kor": "놓치다" },
      { "id": 11, "eng": "later", "kor": "나중에" },
      { "id": 12, "eng": "wet", "kor": "젖은" },
      { "id": 13, "eng": "old", "kor": "오래된, 낡은" },
      { "id": 14, "eng": "favorite", "kor": "가장 좋아하는 것" },
      { "id": 15, "eng": "hamburger", "kor": "햄버거" },
      { "id": 16, "eng": "pass", "kor": "통과하다" },
      { "id": 17, "eng": "softly", "kor": "부드럽게" },
      { "id": 18, "eng": "hockey", "kor": "하키" },
      { "id": 19, "eng": "pack", "kor": "(짐을) 싸다, 챙기다" },
      { "id": 20, "eng": "order", "kor": "주문하다" },
      { "id": 21, "eng": "fail", "kor": "(시험에) 떨어지다" },
      { "id": 22, "eng": "season", "kor": "계절" },
      { "id": 23, "eng": "usually", "kor": "보통" },
      { "id": 24, "eng": "grow", "kor": "기르다, 재배하다" },
      { "id": 25, "eng": "before bed", "kor": "자기 전에" },
      { "id": 26, "eng": "stage", "kor": "무대" },
      { "id": 27, "eng": "careful", "kor": "조심하는" },
      { "id": 28, "eng": "strange", "kor": "이상한" },
      { "id": 29, "eng": "trip", "kor": "여행" }
    ]
  },
  "unit13": {
    "title": "UNIT 13 명령문, and/or ~",
    "words": [
      { "id": 1, "eng": "put on", "kor": "(옷 등을) 입다, 끼다, 신다" },
      { "id": 2, "eng": "catch a cold", "kor": "감기에 걸리다" },
      { "id": 3, "eng": "straight", "kor": "똑바로" },
      { "id": 4, "eng": "open", "kor": "열다; 열리다" },
      { "id": 5, "eng": "cool", "kor": "시원한" },
      { "id": 6, "eng": "take medicine", "kor": "약을 먹다" },
      { "id": 7, "eng": "careful", "kor": "조심하는" },
      { "id": 8, "eng": "break", "kor": "깨뜨리다; 깨지다" },
      { "id": 9, "eng": "dish", "kor": "접시" },
      { "id": 10, "eng": "thirsty", "kor": "목이 마른" },
      { "id": 11, "eng": "healthy", "kor": "건강한" },
      { "id": 12, "eng": "turn", "kor": "돌다" },
      { "id": 13, "eng": "library", "kor": "도서관" },
      { "id": 14, "eng": "take a nap", "kor": "낮잠을 자다" },
      { "id": 15, "eng": "rainbow", "kor": "무지개" },
      { "id": 16, "eng": "on time", "kor": "제시간에" },
      { "id": 17, "eng": "get up", "kor": "일어나다" },
      { "id": 18, "eng": "toothache", "kor": "치통" },
      { "id": 19, "eng": "push", "kor": "밀다" },
      { "id": 20, "eng": "press", "kor": "누르다" },
      { "id": 21, "eng": "worried", "kor": "걱정하는" },
      { "id": 22, "eng": "often", "kor": "자주" },
      { "id": 23, "eng": "have fun", "kor": "재미있게 놀다" },
      { "id": 24, "eng": "fan", "kor": "선풍기" },
      { "id": 25, "eng": "watch out", "kor": "조심하다" },
      { "id": 26, "eng": "fall", "kor": "넘어지다" },
      { "id": 27, "eng": "post office", "kor": "우체국" },
      { "id": 28, "eng": "teachers' room", "kor": "교무실" },
      { "id": 29, "eng": "forget", "kor": "잊다" },
      { "id": 30, "eng": "turn off", "kor": "(전기 등을) 끄다" },
      { "id": 31, "eng": "drop", "kor": "떨어뜨리다" },
      { "id": 32, "eng": "cross", "kor": "건너다" },
      { "id": 33, "eng": "dry", "kor": "말리다" },
      { "id": 34, "eng": "remember", "kor": "기억하다" },
      { "id": 35, "eng": "mistake", "kor": "실수" },
      { "id": 36, "eng": "burn", "kor": "(음식이) 타다" },
      { "id": 37, "eng": "do one's best", "kor": "최선을 다하다" },
      { "id": 38, "eng": "water", "kor": "물을 주다" },
      { "id": 39, "eng": "surprised", "kor": "놀란" },
      { "id": 40, "eng": "get hurt", "kor": "다치다" },
      { "id": 41, "eng": "sunrise", "kor": "일출" }
    ]
  },
  "unit14": {
    "title": "UNIT 14 접속사 because/when/before/after",
    "words": [
      { "id": 1, "eng": "inside", "kor": "안에" },
      { "id": 2, "eng": "popcorn", "kor": "팝콘" },
      { "id": 3, "eng": "dark", "kor": "어두운" },
      { "id": 4, "eng": "leave", "kor": "떠나다" },
      { "id": 5, "eng": "closed", "kor": "문을 닫은" },
      { "id": 6, "eng": "pack", "kor": "(짐을) 싸다, 챙기다" },
      { "id": 7, "eng": "change", "kor": "(옷을) 갈아입다" },
      { "id": 8, "eng": "store", "kor": "가게" },
      { "id": 9, "eng": "each other", "kor": "서로" },
      { "id": 10, "eng": "fight", "kor": "싸움; 싸우다" },
      { "id": 11, "eng": "rainbow", "kor": "무지개" },
      { "id": 12, "eng": "holiday", "kor": "휴일" },
      { "id": 13, "eng": "grade", "kor": "성적" },
      { "id": 14, "eng": "take a shower", "kor": "샤워하다" },
      { "id": 15, "eng": "all night", "kor": "밤새" },
      { "id": 16, "eng": "chocolate", "kor": "초콜릿" },
      { "id": 17, "eng": "dessert", "kor": "디저트, 후식" },
      { "id": 18, "eng": "write in one's diary", "kor": "일기를 쓰다" },
      { "id": 19, "eng": "slowly", "kor": "천천히" },
      { "id": 20, "eng": "hurt", "kor": "아프다" },
      { "id": 21, "eng": "enter", "kor": "들어갈다" },
      { "id": 22, "eng": "knock", "kor": "두드리다" },
      { "id": 23, "eng": "move", "kor": "이사하다" },
      { "id": 24, "eng": "noisy", "kor": "시끄러운" },
      { "id": 25, "eng": "get nervous", "kor": "긴장하다, 초조해지다" },
      { "id": 26, "eng": "exercise", "kor": "운동하다" },
      { "id": 27, "eng": "guest", "kor": "손님" }
    ]
  },
  "unit15": {
    "title": "UNIT 15 접속사 that",
    "words": [
      { "id": 1, "eng": "think", "kor": "생각하다" },
      { "id": 2, "eng": "believe", "kor": "믿다" },
      { "id": 3, "eng": "hope", "kor": "바라다" },
      { "id": 4, "eng": "break one's leg", "kor": "다리가 부러지다" },
      { "id": 5, "eng": "right", "kor": "옳은, 맞음" },
      { "id": 6, "eng": "important", "kor": "중요한" },
      { "id": 7, "eng": "true", "kor": "사실인" },
      { "id": 8, "eng": "wrong", "kor": "잘못된, 틀린" },
      { "id": 9, "eng": "ghost", "kor": "유령, 귀신" },
      { "id": 10, "eng": "real", "kor": "진짜의" },
      { "id": 11, "eng": "friendly", "kor": "친근한" },
      { "id": 12, "eng": "wonderful", "kor": "훌륭한" },
      { "id": 13, "eng": "Santa Claus", "kor": "산타클로스" },
      { "id": 14, "eng": "difficult", "kor": "어려운" },
      { "id": 15, "eng": "liar", "kor": "거짓말쟁이" },
      { "id": 16, "eng": "contest", "kor": "대회" },
      { "id": 17, "eng": "special", "kor": "특별한" },
      { "id": 18, "eng": "mistake", "kor": "실수" }
    ]
  },
  "unit16": {
    "title": "UNIT 16 원급",
    "words": [
      { "id": 1, "eng": "second", "kor": "(시간 단위) 초" },
      { "id": 2, "eng": "dolphin", "kor": "돌고래" },
      { "id": 3, "eng": "human", "kor": "사람, 인간" },
      { "id": 4, "eng": "lamp", "kor": "램프, 등" },
      { "id": 5, "eng": "cheap", "kor": "(값이) 싼" },
      { "id": 6, "eng": "delicious", "kor": "맛있는" },
      { "id": 7, "eng": "Seoul", "kor": "서울" },
      { "id": 8, "eng": "New York", "kor": "뉴욕" },
      { "id": 9, "eng": "thick", "kor": "두꺼운" },
      { "id": 10, "eng": "quiet", "kor": "조용한" },
      { "id": 11, "eng": "idea", "kor": "생각, 아이디어" },
      { "id": 12, "eng": "interesting", "kor": "재미있는" },
      { "id": 13, "eng": "handsome", "kor": "잘생긴" },
      { "id": 14, "eng": "much", "kor": "많이" },
      { "id": 15, "eng": "pumpkin", "kor": "호박" },
      { "id": 16, "eng": "cousin", "kor": "사촌" },
      { "id": 17, "eng": "novel", "kor": "소설" },
      { "id": 18, "eng": "boring", "kor": "재미없는, 지루한" },
      { "id": 19, "eng": "clear", "kor": "분명한, 알아듣기 쉬운" },
      { "id": 20, "eng": "expensive", "kor": "비싼" },
      { "id": 21, "eng": "finger", "kor": "손가락" },
      { "id": 22, "eng": "last", "kor": "지난" },
      { "id": 23, "eng": "important", "kor": "중요한" },
      { "id": 24, "eng": "popular", "kor": "인기 있는" },
      { "id": 25, "eng": "other", "kor": "다른" },
      { "id": 26, "eng": "shy", "kor": "수줍음을 많이 타는" },
      { "id": 27, "eng": "trip", "kor": "여행" }
    ]
  },
  "unit17": {
    "title": "UNIT 17 비교급",
    "words": [
      { "id": 1, "eng": "careful", "kor": "조심스러운" },
      { "id": 2, "eng": "tower", "kor": "탑, 타워" },
      { "id": 3, "eng": "handwriting", "kor": "글씨체" },
      { "id": 4, "eng": "difficult", "kor": "어려운" },
      { "id": 5, "eng": "voice", "kor": "목소리" },
      { "id": 6, "eng": "loud", "kor": "소리가 큰" },
      { "id": 7, "eng": "score", "kor": "점수" },
      { "id": 8, "eng": "Paris", "kor": "파리" },
      { "id": 9, "eng": "Rome", "kor": "로마" },
      { "id": 10, "eng": "fashion", "kor": "패션" },
      { "id": 11, "eng": "famous", "kor": "유명한" },
      { "id": 12, "eng": "close", "kor": "가까운" },
      { "id": 13, "eng": "dangerous", "kor": "위험한" },
      { "id": 14, "eng": "wide", "kor": "넓은" },
      { "id": 15, "eng": "Egypt", "kor": "이집트" },
      { "id": 16, "eng": "puzzle", "kor": "퍼즐" },
      { "id": 17, "eng": "comfortable", "kor": "편안한" },
      { "id": 18, "eng": "design", "kor": "디자인" },
      { "id": 19, "eng": "light", "kor": "가벼운" },
      { "id": 20, "eng": "colorful", "kor": "(색이) 다채로운" }
    ]
  },
  "unit18": {
    "title": "UNIT 18 최상급",
    "words": [
      { "id": 1, "eng": "old", "kor": "나이 많은, 오래된" },
      { "id": 2, "eng": "race", "kor": "경주, 달리기" },
      { "id": 3, "eng": "subject", "kor": "과목" },
      { "id": 4, "eng": "castle", "kor": "성" },
      { "id": 5, "eng": "Europe", "kor": "유럽" },
      { "id": 6, "eng": "Russia", "kor": "러시아" },
      { "id": 7, "eng": "country", "kor": "나라" },
      { "id": 8, "eng": "elephant", "kor": "코끼리" },
      { "id": 9, "eng": "place", "kor": "장소" },
      { "id": 10, "eng": "lucky", "kor": "운이 좋은" },
      { "id": 11, "eng": "close", "kor": "가까운" },
      { "id": 12, "eng": "seat", "kor": "자리, 좌석" },
      { "id": 13, "eng": "stage", "kor": "무대" },
      { "id": 14, "eng": "whale", "kor": "고래" },
      { "id": 15, "eng": "lake", "kor": "호수" },
      { "id": 16, "eng": "interesting", "kor": "재미있는" },
      { "id": 17, "eng": "ride", "kor": "놀이기구" },
      { "id": 18, "eng": "speed", "kor": "속도" },
      { "id": 19, "eng": "scary", "kor": "무서운" },
      { "id": 20, "eng": "roller coaster", "kor": "롤러코스터" },
      { "id": 21, "eng": "merry-go-round", "kor": "회전목마" },
      { "id": 22, "eng": "bumper car", "kor": "범퍼카" },
      { "id": 23, "eng": "pirate", "kor": "해적" },
      { "id": 24, "eng": "area", "kor": "지역" },
      { "id": 25, "eng": "giraffe", "kor": "기린" },
      { "id": 26, "eng": "smell", "kor": "냄새" },
      { "id": 27, "eng": "village", "kor": "마을" },
      { "id": 28, "eng": "rich", "kor": "부유한" },
      { "id": 29, "eng": "laptop", "kor": "노트북" }
    ]
  },
};